// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-uniffi-add.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "RNUniffiAddSpec.h"

@interface UniffiAdd : NSObject <NativeUniffiAddSpec>
#else
#import <React/RCTBridgeModule.h>

@interface UniffiAdd : NSObject <RCTBridgeModule>
#endif

@end