// Generated by uniffi-bindgen-react-native
import installer from './NativeMyRustLib';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/foobar';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as foobar from './generated/foobar';

// Initialize the generated bindings: mostly checksums, but also callbacks.
foobar.default.initialize();

// Export the crates as individually namespaced objects.
export default {
  foobar,
};

