// Generated by uniffi-bindgen-react-native
import installer from './NativeUniffiAdd';

// Register the rust crate with Hermes
installer.installRustCrate();

// Export the generated bindings to the app.
export * from './generated/uniffi_add';

// Now import the bindings so we can:
// - intialize them
// - export them as namespaced objects as the default export.
import * as uniffi_add from './generated/uniffi_add';

// Initialize the generated bindings: mostly checksums, but also callbacks.
uniffi_add.default.initialize();

// Export the crates as individually namespaced objects.
export default {
  uniffi_add,
};

